import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { watch } from "node:fs";
import { utimes } from "node:fs/promises";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Plugin that watches styles.css and triggers hot-reload by touching main.js
const cssWatchPlugin = {
  name: "css-watch",
  setup(build) {
    if (prod) return;

    build.onEnd(async () => {
      // Watch styles.css for changes
      const watcher = watch("styles.css", async (eventType) => {
        if (eventType === "change") {
          console.log("[watch] styles.css changed, triggering reload...");
          // Touch main.js to trigger hot-reload
          const now = new Date();
          try {
            await utimes("main.js", now, now);
          } catch {
            // Ignore if main.js doesn't exist yet
          }
        }
      });

      // Store watcher reference to prevent garbage collection
      process.on("exit", () => watcher.close());
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [cssWatchPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
